name: NCR Mod Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle 8.3
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.3 # Жестко фиксируем стабильную версию!

      - name: Build Mod with Gradle
        run: gradle build

      - name: Upload Finished Mod
        uses: actions/upload-artifact@v4
        with:
          name: NCR_Obereg_Visual_Mod
          path: build/libs/*.jar
